apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgDYFAKEENCRYPTEDVALUEONLYDEMOEXAMPLE...
  template:
    metadata:
      name: my-secret
      namespace: default
    type: Opaque
