name: DevSecOps Pipeline

on:
  push:
    branches: [main]

jobs:
  devsecops:
    name: Run tfsec + trivy + YAML validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec on Terraform code
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working-directory: terraform

      - name: Run Trivy scan on Dockerfile
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
        continue-on-error: true  # in case there's no Dockerfile

      - name: Validate sealed-secret.yaml file
        run: |
          echo "Checking sealed secret YAML format"
          yq eval '.' k8s/sealed-secret.yaml

      - name: Validate deployment.yaml
        run: |
          echo "Validating deployment.yaml format"
          yq eval '.' k8s/deployment.yaml
