name: DevSecOps Pipeline

on:
  push:
    branches: [main]

jobs:
  devsecops:
    name: Run tfsec + trivy + YAML validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec with soft-fail
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform
          soft_fail: true

      - name: Run Trivy scan on Dockerfile (optional)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
        continue-on-error: true  # If no Dockerfile, skip failure

      - name: Validate sealed-secret.yaml (YAML only)
        run: |
          echo "Validating sealed-secret.yaml..."
          yq eval '.' k8s/sealed-secret.yaml

      - name: Validate deployment.yaml (YAML only)
        run: |
          echo "Validating deployment.yaml..."
          yq eval '.' k8s/deployment.yaml
