name: DevSecOps Pipeline

on:
  push:
    branches: [main]

jobs:
  devsecops:
    name: Run tfsec + trivy + YAML validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tfsec on Terraform code
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform  # ✅ Corrected input name

      - name: Run Trivy scan on Dockerfile (optional)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
        continue-on-error: true  # Skips error if no Dockerfile present

      - name: Validate sealed-secret.yaml (YAML check only)
        run: |
          cat k8s/sealed-secret.yaml
          yq eval '.' k8s/sealed-secret.yaml

      - name: Validate deployment.yaml (YAML check only)
        run: |
          cat k8s/deployment.yaml
          yq eval '.' k8s/deployment.yaml
